# Generated by Django 4.2.25 on 2025-10-23 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='books_comme_book_ti_8c1683_idx',
            old_name='books_comme_book_ti_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='books_comme_created_86b679_idx',
            old_name='books_comme_created_def456_idx',
        ),
    ]
