# Generated by Django 4.2.25 on 2025-10-23 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_books_comme_book_ti_abc123_idx_books_comme_book_ti_8c1683_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('autor', models.CharField(max_length=255, verbose_name='Autor')),
                ('editora', models.CharField(blank=True, max_length=255, null=True, verbose_name='Editora')),
                ('ano_publicacao', models.IntegerField(blank=True, null=True, verbose_name='Ano de Publicação')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='ISBN')),
                ('genero', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gênero')),
                ('sinopse', models.TextField(blank=True, null=True, verbose_name='Sinopse')),
                ('capa', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Capa')),
                ('paginas', models.IntegerField(blank=True, null=True, verbose_name='Número de Páginas')),
                ('idioma', models.CharField(default='Português', max_length=50, verbose_name='Idioma')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['-data_cadastro', 'titulo'],
                'indexes': [models.Index(fields=['titulo'], name='books_book_titulo_32044b_idx'), models.Index(fields=['autor'], name='books_book_autor_38cb2c_idx'), models.Index(fields=['genero'], name='books_book_genero_f60907_idx')],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='books.book', verbose_name='Livro'),
        ),
    ]
