# Generated by Django 4.2.25 on 2025-10-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_comment_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Livro em Destaque'),
        ),
    ]
